### ISSUE TITLE
Hostname issues with Splunk provisioning-layer

### ISSUE THREAD

**Issue by ferricoxide** [plus3it/name-computer-formula#5]
See plus3it/splunkforwarder-formula#6 for details.

**Comment by ferricoxide** [comment]
Notes:

1. After the `SystemPrep-LinuxSaltInstall.py` script runs, the `name-computer:computername` gets set to the expected value. &lsqb;GOOD&rsqb;
1. Upon execution of the name-computer formula, the active hostname and the `HOSTNAME` parm in `/etc/sysconfig/network` gets set. &lsqb;GOOD&rsqb;
1. Upon execution of the name-computer formula, the other hostname-containing grains (`fqdn`, `host`, `localhost`) also get set to expected values. &lsqb;GOOD&rsqb;

Translation, I'm not seeing anything (from a stale data standpoint) that would explain the observed behavior.

**Comment by lorengordon** [comment]
Seems like nothing we can do in this formula.
